-- EJERCICIO 1 ------
  
  CREATE SCHEMA COLEGIO;
  
  -- CREAMOS LAS TABLAS 
CREATE TABLE IF NOT EXISTS `COLEGIO`.`ALUMNO` (
  `cod_matricula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `DNI` CHAR(10) NOT NULL,
  `fechadenacimiento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `ALUMNOcol` INT NOT NULL,
  PRIMARY KEY (`cod_matricula`));

CREATE TABLE IF NOT EXISTS `COLEGIO`.`PROFESOR` (
  `idPROFESOR` INT NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `especialidad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPROFESOR`));

CREATE TABLE IF NOT EXISTS `COLEGIO`.`CURSO` (
  `cod_curso` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_curso`));

-- RELACIONAMOS LA TABLAS

CREATE TABLE IF NOT EXISTS `COLEGIO`.`PROFESOR_has_CURSO` (
  `PROFESOR_idPROFESOR` INT NOT NULL,
  `CURSO_cod_curso` INT NOT NULL,
  PRIMARY KEY (`PROFESOR_idPROFESOR`, `CURSO_cod_curso`),
  INDEX `fk_PROFESOR_has
  _CURSO_CURSO1_idx` (`CURSO_cod_curso` ASC) VISIBLE,
  INDEX `fk_PROFESOR_has_CURSO_PROFESOR1_idx` (`PROFESOR_idPROFESOR` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_has_CURSO_PROFESOR1`
    FOREIGN KEY (`PROFESOR_idPROFESOR`)
    REFERENCES `COLEGIO`.`PROFESOR` (`idPROFESOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESOR_has_CURSO_CURSO1`
    FOREIGN KEY (`CURSO_cod_curso`)
    REFERENCES `COLEGIO`.`CURSO` (`cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
      CREATE TABLE IF NOT EXISTS `COLEGIO`.`ALUMNO_has_CURSO` (
  `ALUMNO_cod_matricula` INT NOT NULL,
  `CURSO_cod_curso` INT NOT NULL,
  `id-alumnocurso` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id-alumnocurso`, `ALUMNO_cod_matricula`, `CURSO_cod_curso`),
  INDEX `fk_ALUMNO_has_CURSO_CURSO1_idx` (`CURSO_cod_curso` ASC) VISIBLE,
  INDEX `fk_ALUMNO_has_CURSO_ALUMNO1_idx` (`ALUMNO_cod_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_has_CURSO_ALUMNO1`
    FOREIGN KEY (`ALUMNO_cod_matricula`)
    REFERENCES `COLEGIO`.`ALUMNO` (`cod_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNO_has_CURSO_CURSO1`
    FOREIGN KEY (`CURSO_cod_curso`)
    REFERENCES `COLEGIO`.`CURSO` (`cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE IF NOT EXISTS `COLEGIO`.`ALUMNO_has_CURSO` (
  `ALUMNO_cod_matricula` INT NOT NULL,
  `CURSO_cod_curso` INT NOT NULL,
  `id-alumnocurso` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id-alumnocurso`, `ALUMNO_cod_matricula`, `CURSO_cod_curso`),
  INDEX `fk_ALUMNO_has_CURSO_CURSO1_idx` (`CURSO_cod_curso` ASC) VISIBLE,
  INDEX `fk_ALUMNO_has_CURSO_ALUMNO1_idx` (`ALUMNO_cod_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_has_CURSO_ALUMNO1`
    FOREIGN KEY (`ALUMNO_cod_matricula`)
    REFERENCES `COLEGIO`.`ALUMNO` (`cod_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNO_has_CURSO_CURSO1`
    FOREIGN KEY (`CURSO_cod_curso`)
    REFERENCES `COLEGIO`.`CURSO` (`cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- INTRODUCIMOS VALORES EN LAS TABLAS
  
INSERT INTO ALUMNO VALUES(1, 'alejandro sabio', 4208747,'20/07/1999' , 'alejandro@gmail.com',1);
INSERT INTO ALUMNO VALUES(2, 'alejandro bezus', 4208747,'20/07/1996' , 'alejandrosabio@gmail.com',2);
INSERT INTO ALUMNO VALUES(3, 'alejandro german', 4208747,'20/07/1995' , 'alejandrogerman@gmail.com',3);

INSERT INTO PROFESOR VALUES(1,'robertocarlos@gmail.com','contabilidad', 'Roberto Carlos');
INSERT INTO PROFESOR VALUES(2,'leomessi@gmail.com','futbol', 'Leo Messi');
INSERT INTO PROFESOR VALUES(3,'iniesta@gmail.com','penales', 'Andres Iniesta');

INSERT INTO PROFESOR VALUES(1,'robertocarlos@gmail.com','contabilidad', 'Roberto Carlos');
INSERT INTO PROFESOR VALUES(2,'leomessi@gmail.com','futbol', 'Leo Messi');
INSERT INTO PROFESOR VALUES(3,'iniesta@gmail.com','penales', 'Andres Iniesta');

INSERT INTO CURSO VALUES(1,'contabilidad');
INSERT INTO CURSO VALUES(2,'futbol');
INSERT INTO CURSO VALUES(3,'penales');

CREATE TABLE IF NOT EXISTS `REGIONES`.`PROVINCIA` (
  `CODPROVINCIA` INT NOT NULL,
  `NOMBRE` VARCHAR(40) NULL DEFAULT NULL,
  `CODREGION` INT NULL DEFAULT NULL,
  `PAIS_CODPAIS` INT NOT NULL,
  PRIMARY KEY (`CODPROVINCIA`, `PAIS_CODPAIS`),
  INDEX `fk_PROVINCIA_REGION1_idx` (`PAIS_CODPAIS` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCIA_REGION1`
    FOREIGN KEY (`PAIS_CODPAIS`)
    REFERENCES `REGIONES`.`PAIS` (`CODPAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE IF NOT EXISTS `REGIONES`.`LOCALIDAD` (
  `CODLOCALIDAD` INT NOT NULL,
  `NOMBRE` VARCHAR(40) NULL DEFAULT NULL,
  `CODPROVINCIA` INT NULL DEFAULT NULL,
  `PROVINCIA_CODPROVINCIA` INT NOT NULL,
  PRIMARY KEY (`CODLOCALIDAD`, `PROVINCIA_CODPROVINCIA`),
  INDEX `fk_LOCALIDAD_PROVINCIA_idx` (`PROVINCIA_CODPROVINCIA` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALIDAD_PROVINCIA`
    FOREIGN KEY (`PROVINCIA_CODPROVINCIA`)
    REFERENCES `REGIONES`.`PROVINCIA` (`CODPROVINCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    CREATE TABLE IF NOT EXISTS `REGIONES`.`EMPLEADO` (
  `ID` INT NOT NULL,
  `DNI` CHAR(9) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `FECHANAC` DATE NULL DEFAULT NULL,
  `TELEFONO` CHAR(9) NULL DEFAULT NULL,
  `SALARIO` VARCHAR(20) NULL DEFAULT NULL,
  `CODLOCALIDAD` INT NULL DEFAULT NULL,
  `LOCALIDAD_CODLOCALIDAD` INT NOT NULL,
  `LOCALIDAD_PROVINCIA_CODPROVINCIA` INT NOT NULL,
  PRIMARY KEY (`ID`, `LOCALIDAD_CODLOCALIDAD`, `LOCALIDAD_PROVINCIA_CODPROVINCIA`),
  INDEX `fk_EMPLEADO_LOCALIDAD1_idx` (`LOCALIDAD_CODLOCALIDAD` ASC, `LOCALIDAD_PROVINCIA_CODPROVINCIA` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_CODLOCALIDAD` , `LOCALIDAD_PROVINCIA_CODPROVINCIA`)
    REFERENCES `REGIONES`.`LOCALIDAD` (`CODLOCALIDAD` , `PROVINCIA_CODPROVINCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
-- EJERCICIO 2
CREATE SCHEMA REGIONES;
CREATE TABLE IF NOT EXISTS `REGIONES`.`PAIS` (
  `CODPAIS` INT NOT NULL,
  `NOMBRE` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`CODPAIS`));
  
CREATE TABLE IF NOT EXISTS `REGIONES`.`PROVINCIA` (
  `CODPROVINCIA` INT NOT NULL,
  `NOMBRE` VARCHAR(40) NULL DEFAULT NULL,
  `CODREGION` INT NULL DEFAULT NULL,
  `PAIS_CODPAIS` INT NOT NULL,
  PRIMARY KEY (`CODPROVINCIA`, `PAIS_CODPAIS`),
  INDEX `fk_PROVINCIA_REGION1_idx` (`PAIS_CODPAIS` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCIA_REGION1`
    FOREIGN KEY (`PAIS_CODPAIS`)
    REFERENCES `REGIONES`.`PAIS` (`CODPAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE IF NOT EXISTS `REGIONES`.`LOCALIDAD` (
  `CODLOCALIDAD` INT NOT NULL,
  `NOMBRE` VARCHAR(40) NULL DEFAULT NULL,
  `CODPROVINCIA` INT NULL DEFAULT NULL,
  `PROVINCIA_CODPROVINCIA` INT NOT NULL,
  PRIMARY KEY (`CODLOCALIDAD`, `PROVINCIA_CODPROVINCIA`),
  INDEX `fk_LOCALIDAD_PROVINCIA_idx` (`PROVINCIA_CODPROVINCIA` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALIDAD_PROVINCIA`
    FOREIGN KEY (`PROVINCIA_CODPROVINCIA`)
    REFERENCES `REGIONES`.`PROVINCIA` (`CODPROVINCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    CREATE TABLE IF NOT EXISTS `REGIONES`.`EMPLEADO` (
  `ID` INT NOT NULL,
  `DNI` CHAR(9) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `TELEFONO` CHAR(20) NULL DEFAULT NULL,
  `FECHAALTA` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `LOCALIDAD_CODLOCALIDAD` INT NOT NULL,
  `LOCALIDAD_PROVINCIA_CODPROVINCIA` INT NOT NULL,
  PRIMARY KEY (`ID`, `LOCALIDAD_CODLOCALIDAD`, `LOCALIDAD_PROVINCIA_CODPROVINCIA`),
  INDEX `fk_EMPLEADO_LOCALIDAD1_idx` (`LOCALIDAD_CODLOCALIDAD` ASC, `LOCALIDAD_PROVINCIA_CODPROVINCIA` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_CODLOCALIDAD` , `LOCALIDAD_PROVINCIA_CODPROVINCIA`)
    REFERENCES `REGIONES`.`LOCALIDAD` (`CODLOCALIDAD` , `PROVINCIA_CODPROVINCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


INSERT INTO PAIS VALUES(1, 'ARGENTINA');
INSERT INTO PAIS VALUES(2, 'PARAGUAY');
INSERT INTO PAIS VALUES(3, 'BRASIL');

INSERT INTO PROVINCIA VALUES(1, 'CORRIENTES',1);
INSERT INTO PROVINCIA VALUES(2, 'ENCARNACION',2);
INSERT INTO PROVINCIA VALUES(3, 'SAN PABLO',3);

INSERT INTO LOCALIDAD VALUES(1, 'VIRASORO',3320,1);
INSERT INTO LOCALIDAD VALUES(2, 'CARAUTE',3345,2);
INSERT INTO LOCALIDAD VALUES(3, 'FERRUGEN',3453,3);

INSERT INTO EMPLEADOS VALUES(1, 4208747, 'alejandro terra','20/07/1999', '20-10-1996', 'alejandrorer@gmail.com',1,1);
INSERT INTO EMPLEADOS VALUES(2, 4208747, 'alejandro torero','20/07/1996', '20-10-1994', 'alejandrorewrw@gmail.com',1,1);
INSERT INTO EMPLEADOS VALUES(3, 4208747, 'alejandro cartera','20/07/1995', '20-10-1999', 'alejandrowrwer@gmail.com',1,1);





